<?php

return PhpCsFixer\Config::create()
        ->setRules([
            '@PSR2' => true,
            'array_syntax' => ['syntax' => 'short'],
            'blank_line_after_namespace' => true,
            'blank_line_before_return' => true,
            'blank_line_after_opening_tag' => true,
            'no_multiline_whitespace_before_semicolons' => true,
            'no_short_echo_tag' => true,
            'no_unused_imports' => true,
            'no_useless_else' => true,
            'no_whitespace_before_comma_in_array' => true,
            'ordered_imports' => [
                'sortAlgorithm' => 'length',
            ],
            'php_unit_construct' => false,
            'php_unit_dedicate_assert' => false,
            'php_unit_fqcn_annotation' => true,
            'php_unit_strict' => false,
            'php_unit_test_class_requires_covers' => false,
            'phpdoc_add_missing_param_annotation' => [
                'only_untyped' => false,
            ],
            'phpdoc_annotation_without_dot' => false,
            'phpdoc_indent' => true,
            'phpdoc_inline_tag' => true,
            'phpdoc_no_access' => true,
            'phpdoc_no_alias_tag' => [
                'type' => 'var',
            ],
            'phpdoc_no_package' => true,
            'phpdoc_return_self_reference' => true,
            'phpdoc_order' => true,
            'phpdoc_separation' => true,
            'phpdoc_single_line_var_spacing' => true,
            'phpdoc_summary' => true,
            'phpdoc_to_comment' => false,
            'phpdoc_trim' => true,
            'phpdoc_types' => true,
            'phpdoc_var_without_name' => true,
            'phpdoc_indent' => true,
            'phpdoc_no_package' => true,
            'phpdoc_order' => true,
            'phpdoc_separation' => true,
            'phpdoc_single_line_var_spacing' => true,
            'phpdoc_trim' => true,
            'phpdoc_var_without_name' => true,
            'phpdoc_to_comment' => true,
            'single_quote' => true,
            'ternary_operator_spaces' => true,
            'trailing_comma_in_multiline_array' => true,
            'trim_array_spaces' => true,
            'whitespace_after_comma_in_array' => true,
        ])
        ->setLineEnding("\n");
